In [1]:
#Câu 1:
import numpy as np
import math
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([[2, -1, 3],
              [1, 4, -2],
              [0, 2, 5]])
sum_AB = A + B
scalar_mult = 2 * A + 3 * B
dot_product = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = dot_product / (norm_A * norm_B)
angle_deg = math.degrees(math.acos(cos_theta))
angle_deg = round(angle_deg, 3)
CC_T = np.dot(C, C.T)
print("a) A + B =", sum_AB)
print("   2A + 3B =", scalar_mult)
print("b) Tích vô hướng A · B =", dot_product)
print("   Góc giữa hai vector =", angle_deg, "độ")
print("c) Tích ma trận C · Cᵀ =\n", CC_T)

a) A + B = [2 3 1 6]
   2A + 3B = [ 3 11  2 14]
b) Tích vô hướng A · B = -5
   Góc giữa hai vector = 99.594 độ
c) Tích ma trận C · Cᵀ =
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


In [2]:
#Câu 2:
import numpy as np
from numpy.linalg import matrix_rank, det
M = np.array([
    [2, -1, 3, 0],
    [1, 4, -2, 5],
    [0, 2, 6, -3],
    [-1, 0, 1, 4]
])
N = np.array([
    [1, 3, -2, 0],
    [4, -1, 5, 2],
    [0, 2, 3, -1],
    [-3, 1, 0, 4]
])
product_MN = np.dot(M, N)
det_M = None
if M.shape[0] == M.shape[1]:
    det_M = round(np.linalg.det(M), 3)
else:
    det_M = "Không tính được vì M không phải là ma trận vuông"
rank_N = matrix_rank(N)
print("a) M × N =\n", product_MN)
print("b) Định thức của M =", det_M)
print("c) Hạng của N =", rank_N)

a) M × N =
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]
b) Định thức của M = 409.0
c) Hạng của N = 4


In [3]:
#câu 3:
import numpy as np
P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]
])

b = np.array([6, 8, 3, 7])
try:
    P_inv = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo của P:\n", P_inv)
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch!")
x = np.dot(P_inv, b)
x = np.round(x, 3)
print("b) Nghiệm của hệ phương trình:\n", x)
check = np.dot(P, x)
print("c) Kiểm tra lại nghiệm P · x:\n", check)
print("   Vector ban đầu b:\n", b)

a) Ma trận nghịch đảo của P:
 [[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]
b) Nghiệm của hệ phương trình:
 [2.    1.714 0.429 0.857]
c) Kiểm tra lại nghiệm P · x:
 [6.    7.998 3.002 7.   ]
   Vector ban đầu b:
 [6 8 3 7]


In [5]:
#Câu 4:
import numpy as np
from numpy.linalg import eig, norm
Q = np.array([
    [5, -2, 1],
    [0, 3, -1],
    [2, 0, 4]
])
eigenvalues, eigenvectors = eig(Q)
eigenvalues = np.round(eigenvalues, 3)
print("a) Các giá trị riêng của Q:", eigenvalues)
print("b) Các vector riêng tương ứng:")
for i in range(len(eigenvalues)):
    print(f"   Giá trị riêng {eigenvalues[i]} ⇒ vector riêng:")
    print(np.round(eigenvectors[:, i], 3))
print("c) Chuẩn hóa các vector riêng (độ dài = 1):")
for i in range(eigenvectors.shape[1]):
    vec = eigenvectors[:, i]
    vec_normalized = vec / norm(vec)
    print(f"   Vector chuẩn hóa {i+1}:", np.round(vec_normalized, 3))

a) Các giá trị riêng của Q: [6.355+0.j    2.822+1.077j 2.822-1.077j]
b) Các vector riêng tương ứng:
   Giá trị riêng (6.355+0j) ⇒ vector riêng:
[ 0.748+0.j -0.189+0.j  0.636+0.j]
   Giá trị riêng (2.822+1.077j) ⇒ vector riêng:
[-0.374+0.342j  0.095+0.574j  0.636+0.j   ]
   Giá trị riêng (2.822-1.077j) ⇒ vector riêng:
[-0.374-0.342j  0.095-0.574j  0.636-0.j   ]
c) Chuẩn hóa các vector riêng (độ dài = 1):
   Vector chuẩn hóa 1: [ 0.748+0.j -0.189+0.j  0.636+0.j]
   Vector chuẩn hóa 2: [-0.374+0.342j  0.095+0.574j  0.636+0.j   ]
   Vector chuẩn hóa 3: [-0.374-0.342j  0.095-0.574j  0.636-0.j   ]


In [9]:
#Câu 5:
import numpy as np
R = np.array([
    [4, -1, 2],
    [1, 3, -2],
    [0, 2, 5]
])
b = np.array([12, 5, 9])
x = np.linalg.solve(R, b)
print("a) Nghiệm của hệ Rx = b là:")
print(np.round(x, 3))
try:
    R_inv = np.linalg.inv(R)
    x_inv = np.dot(R_inv, b)
    print("\nb) Ma trận R khả nghịch.")
    print("   Nghiệm tìm bằng R⁻¹ * b là:")
    print(np.round(x_inv, 3))
    print("   So sánh với np.linalg.solve:", np.allclose(x, x_inv))
except np.linalg.LinAlgError:
    print("\nb) Ma trận R không khả nghịch.")
fro_norm = np.linalg.norm(R, 'fro')
print("\nc) Chuẩn Frobenius của ma trận R là:", round(fro_norm, 3))

a) Nghiệm của hệ Rx = b là:
[2.788 1.529 1.188]

b) Ma trận R khả nghịch.
   Nghiệm tìm bằng R⁻¹ * b là:
[2.788 1.529 1.188]
   So sánh với np.linalg.solve: True

c) Chuẩn Frobenius của ma trận R là: 8.0
