BÀI TẬP TRÊN LỚP

In [1]:
#1.2.Các bài toán tính toán
import numpy as np
u = np.array([2, -1, 5, 0])
v = np.array([4, 3, 1, -1])
w = np.array([-6, 2, 0, 3])
x = 2*u - (v + 3*w)
print(x)

[ 18 -11   9  -8]


In [2]:
x = 0.5*(2*u-v-3*w)
print (x)

[ 9.  -5.5  4.5 -4. ]


In [3]:
from numpy import linalg
A = np.matrix([[0, -1, 3], [1, 1, 1], [4, 2, 2]])
B = np.array([-1, -2, -2])
X = np.linalg.solve(A, B)
print(X)

[ 1. -2. -1.]


In [7]:
A = np.matrix([[1, 0],[0, 0]])
B = np.matrix([[0, 0], [0, 1]])
from numpy import linalg as LA

In [10]:
LA.inv(A)

LinAlgError: Singular matrix

In [11]:
LA.inv(B)

LinAlgError: Singular matrix

In [12]:
LA.inv(A+B)

matrix([[1., 0.],
        [0., 1.]])

In [13]:
LA.det(A)

np.float64(0.0)

In [14]:
LA.det(B)

np.float64(0.0)

In [15]:
LA.det(A + B)

np.float64(1.0)

In [16]:
import sympy as sp
x, y = sp.symbols('x y')
A = sp.Matrix([[x, y], [y, x]])
x1, y1 = sp.symbols('x1 y1')
A1 = sp.Matrix([[x1, y1], [y1, x1]])
x2, y2 = sp.symbols('x2 y2')
A2 = sp.Matrix([[x2, y2], [y2, x2]])
A1.T

Matrix([
[x1, y1],
[y1, x1]])

In [17]:
(A1+A2).T

Matrix([
[x1 + x2, y1 + y2],
[y1 + y2, x1 + x2]])

In [18]:
((A1+A2).T).equals(A1+A2)

True

In [19]:
c = sp.symbols('c')
print (c*A)

Matrix([[c*x, c*y], [c*y, c*x]])


In [20]:
((c*A).T).equals(c*A)

True

In [21]:
import numpy as np
v1 = np.array([1, 2, 3])
v2 = np.array([0, 1, 2])
v3 = np.array([-1, 0, 1])
w1 = np.array([1, 1, 1])
A = np.column_stack((v1, v2, v3))
try:
    c = np.linalg.solve(A, w1)
    print("a. w1 là tổ hợp tuyến tính của v1, v2, v3 với hệ số:", c)
except np.linalg.LinAlgError:
    print("a. w1 không là tổ hợp tuyến tính của v1, v2, v3")

a. w1 là tổ hợp tuyến tính của v1, v2, v3 với hệ số: [ 5.00000000e-01 -1.66533454e-16 -5.00000000e-01]


In [22]:
w2 = np.array([1, -2, 2])

try:
    c = np.linalg.solve(A, w2)
    print("b. w2 là tổ hợp tuyến tính của v1, v2, v3 với hệ số:", c)
except np.linalg.LinAlgError:
    print("b. w2 không là tổ hợp tuyến tính của v1, v2, v3")

b. w2 là tổ hợp tuyến tính của v1, v2, v3 với hệ số: [ 3.15251974e+16 -6.30503948e+16  3.15251974e+16]


In [23]:
import sympy as sp
c1, c2, c3 = sp.symbols('c1 c2 c3')
sp.solve([c1 - 2*c3, 2*c1 + c2, 3*c1 + 2*c2 + c3], [c1, c2, c3])

{c1: 0, c2: 0, c3: 0}

In [24]:
import sympy as sp
c1, c2 = sp.symbols('c1 c2')
u1, u2 = sp.symbols('u1 u2')
sp.solve([c1 + c2 - u1, c1 - c2 - u2])

{c1: u1/2 + u2/2, c2: u1/2 - u2/2}

In [25]:
u1 = 0
u2 = 0
sp.solve([c1 + c2 - u1, c1 - c2 - u2])

{c1: 0, c2: 0}

In [26]:
#2.2.Bài toán ứng dụng: Ma trận biến đổi (ảnh/font chữ/…)
import numpy as np
P = np.array([[0, 0, 3, 3, 1, 1, 2, 2, 1, 1],
              [0, 5, 5, 4, 4, 3, 3, 2, 2, 0]])
vecdelta = np.array([4, 2])
P_caua = (P.T + vecdelta).T
print(P_caua)

[[4 4 7 7 5 5 6 6 5 5]
 [2 7 7 6 6 5 5 4 4 2]]


In [27]:
import numpy as np
P = np.array([[0, 0, 3, 3, 1, 1, 2, 2, 1, 1],
              [0, 5, 5, 4, 4, 3, 3, 2, 2, 0]])
vecdelta = np.array([4, -2])
matran_biendoi = np.array([[1.0, 0.0],
                           [0.0, 2.0]])
P_caub = (P.T @ matran_biendoi + vecdelta).T
print(P_caub)

[[ 4.  4.  7.  7.  5.  5.  6.  6.  5.  5.]
 [-2.  8.  8.  6.  6.  4.  4.  2.  2. -2.]]


In [28]:
import numpy as np
def transform_point(x, y, a, b):
    M = np.array([
        [-1, 0],
        [ 0, 1]
    ])
    P = np.array([x, y])
    T = np.array([a, b])
    new_point = M @ P + T
    return new_point
x, y = 3, 2
a, b = 5, -1
new_x, new_y = transform_point(x, y, a, b)
print(f"Điểm sau biến đổi: ({new_x}, {new_y})")

Điểm sau biến đổi: (2, 1)


In [29]:
import numpy as np
def shear_translate_point(x, y, p, q, a, b):
    M = np.array([
        [1, p],
        [q, 1]])
    P = np.array([x, y])
    T = np.array([a, b])
    new_point = M @ P + T
    return new_point
x, y = 3, 2
p, q = 0.5, 0
a, b = 1, -1
new_x, new_y = shear_translate_point(x, y, p, q, a, b)
print(f"Điểm sau biến đổi: ({new_x}, {new_y})")

Điểm sau biến đổi: (5.0, 1.0)


In [30]:
import numpy as np
def reflect_y0(x, y):
    M = np.array([
        [-1, 0],
        [ 0, 1]
    ])
    P = np.array([x, y])
    new_point = M @ P
    return new_point
x, y = 3, 2
new_x, new_y = reflect_y0(x, y)
print(f"Đối xứng qua y=0: ({new_x}, {new_y})")

Đối xứng qua y=0: (-3, 2)


In [31]:
def reflect_y_eq_x(x, y):
    M = np.array([
        [0, 1],
        [1, 0]])
    P = np.array([x, y])
    new_point = M @ P
    return new_point
new_x, new_y = reflect_y_eq_x(x, y)
print(f"Đối xứng qua y=x: ({new_x}, {new_y})")


Đối xứng qua y=x: (2, 3)


In [32]:
#3.1.Kiểm tra một ánh xạ là ánh xạ tuyến tính
import sympy as sp
from sympy import lambdify
x1, x2, x3 = sp.symbols('x1 x2 x3')
bieuthuc1 = x1 - x2 + x3
f1 = lambdify([x1, x2, x3], bieuthuc1, 'numpy')
a, b, c = sp.symbols('a b c')
d, e, f = sp.symbols('d e f')
f1(a, b, c)

a - b + c

In [33]:
f1(d, e, f)

d - e + f

In [34]:
f1(a+d, b+e, c+f)

a - b + c + d - e + f

In [35]:
f1(a,b,c) + f1(d,e,f) == f1(a+d, b+e, c+f)

True

In [36]:
(f1(a,b,c) + f1(d,e,f)).equals( f1(a+d, b+e, c+f))

True

In [37]:
q = sp.symbols('q')
(q*f1(a,b,c) + f1(d,e,f)).equals(f1(q*a+d, q*b+e, q*c+f).expand())

True

In [38]:
bieuthuc2 = 2*x2 + 3* x3
f2 = lambdify([x1, x2, x3], bieuthuc2, 'numpy')
(q*f2(a,b,c) + f2(d,e,f)).equals(f2(q*a+d, q*b+e, q*c+f).expand())

True

In [39]:
#3.2.Tìm tổ hợp tuyến tính cho một ánh xạ tuyến tính
import numpy as np
u1 = np.array([1, 2])
u2 = np.array([3, 5])
u3 = np.array([4, 5])
A = np.column_stack((u1, u2))
b = u3
alpha_beta = np.linalg.solve(A, b)
alpha, beta = alpha_beta
print(f"α = {alpha}, β = {beta}")
f_u1 = np.array([1, 1, 2])
f_u2 = np.array([4, 2, 1])
f_u3 = alpha * f_u1 + beta * f_u2
print(f"f(u3) = {f_u3}")

α = -5.0, β = 3.0
f(u3) = [ 7.  1. -7.]


In [40]:
#3.3.Tìm ánh xạ tuyến tính
import sympy as sp
a, b = sp.symbols('a b')
x, y = sp.symbols('x y')
sp.solve([a + 3*b - x, 2*a + 5*b - y], [a, b])

{a: -5*x + 3*y, b: 2*x - y}

In [41]:
fu1 = np.array([1, 1, 2])
fu2 = np.array([4, 2, 1])
fu = a*fu1 + b*fu2
print(fu)

[a + 4*b a + 2*b 2*a + b]


In [42]:
fu = a.subs(a, -5*x + 3*y)*fu1 + b.subs(b, 2*x - y)*fu2
print (fu)

[3*x - y -x + y -8*x + 5*y]


In [43]:
#3.4.Tìm nhân của ánh xạ tuyến tính
x1, x2, x3 = sp.symbols('x1 x2 x3')
sp.solve([x1+x2-x3, 2*x1+3*x2-x3, 3*x1+5*x2-x3],[x1, x2, x3])

{x1: 2*x3, x2: -x3}

In [44]:
#3.6. Ma trận của ánh xạ tuyến tính trong cặp cơ sở
import numpy as np
u1 = np.array([-1, 1])
u2 = np.array([1, 0])
v1 = np.array([1, 2])
v2 = np.array([1, 3])
def f(x):
    return np.array([x[0] - x[1], x[0]])
fu1 = f(u1)  # f(-1,1) = (-2, -1)
fu2 = f(u2)  # f(1,0)  = (1, 1)
F = np.column_stack((v1, v2))
coords_fu1 = np.linalg.solve(F, fu1)
coords_fu2 = np.linalg.solve(F, fu2)
A = np.column_stack((coords_fu1, coords_fu2))
print("Tọa độ [f(u1)]_F:", coords_fu1)
print("Tọa độ [f(u2)]_F:", coords_fu2)
print("Ma trận ánh xạ A = [f]^F_B:\n", A)

Tọa độ [f(u1)]_F: [-5.  3.]
Tọa độ [f(u2)]_F: [ 2. -1.]
Ma trận ánh xạ A = [f]^F_B:
 [[-5.  2.]
 [ 3. -1.]]


In [45]:
import numpy as np
import math
from scipy import linalg as LA
B = np.matrix([[1.0 / math.sqrt(2), 1.0 / math.sqrt(2)],
               [-1.0 / math.sqrt(2), 1.0 / math.sqrt(2)]])
LA.orth(B)

array([[-0.70710678,  0.70710678],
       [ 0.70710678,  0.70710678]])

In [46]:
1.0/math.sqrt(2)

0.7071067811865475

In [47]:
#4. Bài toán ứng dụng: Đường conic và các phép biến đổi
import sympy as sp
x, y, xp, yp = sp.symbols('x y x_prime y_prime')
theta = sp.pi / 4
cos_t = sp.cos(theta)
sin_t = sp.sin(theta)
x_sub = cos_t * xp - sin_t * yp
y_sub = sin_t * xp + cos_t * yp
f = 5*x**2 - 6*x*y + 5*y**2 + 14*x - 2*sp.sqrt(2)*y + 18
f_transformed = f.subs({x: x_sub, y: y_sub})
f_transformed_simplified = sp.simplify(f_transformed)
print("Phương trình sau khi biến đổi là:")
sp.pprint(f_transformed_simplified)

Phương trình sau khi biến đổi là:
        2                                    2                              
2⋅xₚᵣᵢₘₑ  - 2⋅xₚᵣᵢₘₑ + 7⋅√2⋅xₚᵣᵢₘₑ + 8⋅yₚᵣᵢₘₑ  - 7⋅√2⋅yₚᵣᵢₘₑ - 2⋅yₚᵣᵢₘₑ + 18


BÀI TẬP VỀ

In [49]:
#câu 1
import sympy as sp
def g(x, y, z):
    return (x + y, z + 2, 0)
u = sp.Matrix([1, 2, 3])
v = sp.Matrix([4, 5, 6])
c = 3
g_u = sp.Matrix(g(*u))
g_v = sp.Matrix(g(*v))
g_u_plus_v = sp.Matrix(g(*(u + v)))
g_u_plus_g_v = g_u + g_v
g_cu = sp.Matrix(g(*(c * u)))
c_g_u = c * g_u
print("g(u + v) == g(u) + g(v)?", g_u_plus_v == g_u_plus_g_v)
print("g(c * u) == c * g(u)?", g_cu == c_g_u)

g(u + v) == g(u) + g(v)? False
g(c * u) == c * g(u)? False


In [50]:
#câu 2
import numpy as np
theta_deg = 45
theta = np.radians(theta_deg)
P = np.array([[np.cos(theta), np.sin(theta)],
              [-np.sin(theta), np.cos(theta)]])
X = np.array([[2], [3]])
X_new = P @ X
print("Toạ độ điểm sau khi biến đổi (trong cơ sở xoay):")
print(X_new)

Toạ độ điểm sau khi biến đổi (trong cơ sở xoay):
[[3.53553391]
 [0.70710678]]


In [53]:
#câu 3
import sympy as sp
def T(v1, v2):
    return (v1 - v2, v1 + 2*v2)
u = sp.Matrix([1, 2])
v = sp.Matrix([3, -1])
c = 4
T_u = sp.Matrix(T(*u))
T_v = sp.Matrix(T(*v))
T_u_plus_v = sp.Matrix(T(*(u + v)))
T_u_plus_T_v = T_u + T_v
T_cu = sp.Matrix(T(*(c * u)))
c_T_u = c * T_u
print("T(u + v) == T(u) + T(v)", T_u_plus_v == T_u_plus_T_v)
print("T(c * u) == c * T(u)", T_cu == c_T_u)

T(u + v) == T(u) + T(v) True
T(c * u) == c * T(u) True


In [52]:
#câu 4
import sympy as sp
import numpy as np
a, b, c = 13, -10, 13
A = sp.Matrix([[a, b/2],
               [b/2, c]])
eigenvals = A.eigenvals()
print("Trị riêng λ1, λ2 là:")
sp.pprint(eigenvals)
A_np = np.array([[a, b/2], [b/2, c]])
eigvals, eigvecs = np.linalg.eigh(A_np)
theta_rad = np.arctan2(eigvecs[1, 0], eigvecs[0, 0])
theta_deg = np.degrees(theta_rad)
print(f"Góc xoay là: {theta_deg:.2f} độ")

Trị riêng λ1, λ2 là:
{8.0: 1, 18.0: 1}
Góc xoay là: -135.00 độ


In [56]:
#bài toán
import numpy as np
import sympy as sp
a, b, c = 13, -10, 13
d, e, f = 0, 0, -72
A = np.array([[a, b/2], [b/2, c]])
eigvals, eigvecs = np.linalg.eigh(A)
print("Trị riêng (λ1, λ2):", eigvals)
theta = np.arctan2(eigvecs[1, 0], eigvecs[0, 0])
theta_deg = np.degrees(theta)
print(f"Góc xoay: {theta_deg:.2f} độ")
x, y = sp.symbols('x y')
cos_theta = sp.sqrt(2)/2
sin_theta = cos_theta
x_new = cos_theta * x - sin_theta * y
y_new = sin_theta * x + cos_theta * y
expr = 13 * x**2 - 10 * x * y + 13 * y**2 - 72
expr_rotated = expr.subs({x: x_new, y: y_new})
expr_rotated = sp.simplify(expr_rotated)
print("Phương trình sau khi xoay:")
sp.pprint(expr_rotated)
expr_normalized = sp.Eq(expr_rotated, 0)
sp.pprint(expr_normalized)

Trị riêng (λ1, λ2): [ 8. 18.]
Góc xoay: -135.00 độ
Phương trình sau khi xoay:
          2                                                    2     
13⋅(x + y)    5⋅√2⋅(x + y)⋅(-x + √2⋅x - y)   13⋅(-x + √2⋅x - y)      
─────────── - ──────────────────────────── + ─────────────────── - 72
     2                     2                          4              
          2                                                    2         
13⋅(x + y)    5⋅√2⋅(x + y)⋅(-x + √2⋅x - y)   13⋅(-x + √2⋅x - y)          
─────────── - ──────────────────────────── + ─────────────────── - 72 = 0
     2                     2                          4                  
