BÀI TẬP TRÊN LỚP

In [10]:
#1. Định thức và các tính chất
import numpy as np
n = 4
X = np.array(range(1,n+1))
sigma = np.array([4,3,2,1])
def sgn_by_def(sigma):
  ket_qua = 1.0
  for i in range(len(X) - 1):
    for j in range(i+1, len(X)):
      ket_qua = ket_qua * ((X[i]-X[j])/(sigma[i]-sigma[j]))
  return int(ket_qua)
sigma = np.array([2,1,3,4])
sgn_by_def(sigma)

-1

In [11]:
sigma = np.array([1,2,3,4])
sgn_by_def(sigma)

1

In [12]:
sigma = np.array([4,3,2,1])
sgn_by_def(sigma)

1

In [13]:
from itertools import permutations
n = 3
X = []
for i in range(1, n+1):
  X.append(i)
Sn = list(permutations(X))
print(Sn)

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [17]:
#Đoạn code 1:
def sgn_by_def(sigma):
    count = 0
    n = len(sigma)
    for i in range(n):
        for j in range(i + 1, n):
            if sigma[i] > sigma[j]:
                count += 1
    return -1 if count % 2 else 1

def phatsinh_dinhthuc(n):
    X = list(range(1, n + 1))
    Sn = list(permutations(X))
    dinhthuc = ""
    for sn in Sn:
        product = ""
        for i in range(n):
            product += "a" + str(i + 1) + str(sn[i])
        dau = sgn_by_def(sn)
        product = ("+" if dau == 1 else "-") + product
        dinhthuc += product
    return dinhthuc

print(phatsinh_dinhthuc(2))


+a11a22-a12a21


In [18]:
print(phatsinh_dinhthuc(3))

+a11a22a33-a11a23a32-a12a21a33+a12a23a31+a13a21a32-a13a22a31


In [25]:
#Đoạn code 2:
def tinhtoan_dinhthuc(A):
  X = []
  import math
  n = int(math.sqrt(A.size))
  for i in range(1, n+1):
    X.append(i)
  Sn = list(permutations(X))
  dinhthuc = 0
  for sn in Sn:
    sigma = np.array([1])
    sigma.resize([n])
    product = 1
    for i in range(1, n+1):
      sigma[sn.index(i)] = i
      product = product * A[i-1][sn.index(i)]
    dau = sgn_by_def(sigma)
    if (dau != 1):
      product = product * (-1)
    dinhthuc = dinhthuc + product
  return dinhthuc
matran = np.array([[3,5,-8],[4,12,-1],[2,5,3]])
print(tinhtoan_dinhthuc(matran))

85


In [26]:
#3. Quy tắc Cramer
import numpy as np
A = np.array([[4, -2],[3, -5]])
A1 = np.array([[10, -2],[11, -5]])
A2 = np.array([[4, 10],[3, 11]])
from scipy import linalg
detA = linalg.det(A)
detA1 = linalg.det(A1)
detA2 = linalg.det(A2)
print(detA, detA1, detA2)

-14.0 -28.0 14.000000000000004


In [27]:
if (detA != 0):
  x1 = detA1 / detA
  x2 = detA2 / detA
  print ("Hai nghiệm của phương trình là: ", x1, x2)

Hai nghiệm của phương trình là:  2.0 -1.0000000000000002


In [28]:
print(tinhtoan_dinhthuc(A))

-14


In [29]:
print(tinhtoan_dinhthuc(A1))

-28


In [30]:
print(tinhtoan_dinhthuc(A2))

14


In [35]:
#Hệ ba phương trình tuyến tính bậc 1:
import numpy as np
A = np.array([[-1, 2, -3],
              [2, -2, 1],
              [3, -4, 4]])

B = np.array([1, 3, 2])

rank_A = np.linalg.matrix_rank(A)
augmented_matrix = np.column_stack((A, B))
rank_augmented = np.linalg.matrix_rank(augmented_matrix)
if rank_A == rank_augmented:
    if rank_A == A.shape[1]:
        solution = np.linalg.solve(A, B)
        print("Hệ có nghiệm duy nhất:")
        print(f"a = {solution[0]}")
        print(f"e = {solution[1]}")
        print(f"f = {solution[2]}")
    else:
        print("Hệ có vô số nghiệm")
else:
    print("Hệ vô nghiệm")

Hệ có vô số nghiệm


In [43]:
#Tính toán theo phương pháp scipy.linalg.det:
from scipy.linalg import det
detA = det(A)

AX = np.array([B, A[:,1], A[:,2]]).T
AY = np.array([A[:,0], B, A[:,2]]).T
AZ = np.array([A[:,0], A[:,1], B]).T

detX = det(AX)
detY = det(AY)
detZ = det(AZ)

if detA == 0:
    print("Hệ phương trình vô nghiệm hoặc vô số nghiệm (định thức = 0)")
else:
  x, y, z = detX/detA, detY/detA, detZ/detA
  print("Nghiệm của phương trình: x =", x, "y =", y, "z =", z)


Hệ phương trình vô nghiệm hoặc vô số nghiệm (định thức = 0)


In [39]:
#Tính toán theo phương pháp tinhtoan_dinhthuc()
detA = tinhtoan_dinhthuc(A)
detX = tinhtoan_dinhthuc(AX)
detY = tinhtoan_dinhthuc(AY)
detZ = tinhtoan_dinhthuc(AZ)
if detA == 0:
    print("Hệ phương trình vô nghiệm hoặc vô số nghiệm (định thức = 0)")
else:
    x = detX / detA
    y = detY / detA
    z = detZ / detA
    print("Nghiệm", "x =", x, "y =", y, "z =", z)

Hệ phương trình vô nghiệm hoặc vô số nghiệm (định thức = 0)


In [45]:
import sympy as sp
TG = sp.Matrix([[1, 0, 1],[4, 3, 1],[2, 2, 1]])
1/2*TG.det()

1.50000000000000

In [47]:
#Ứng dụng 1:
def tinh_dien_tich_da_giac(dinh):
    n = len(dinh)
    dien_tich = 0
    for i in range(n):
        x1, y1 = dinh[i]
        x2, y2 = dinh[(i + 1) % n]
        dien_tich += (x1 * y2) - (x2 * y1)
    return abs(dien_tich) / 2
dinh = [(4,10), (9,7), (11,2), (2,2), (4,10)]
dien_tich = tinh_dien_tich_da_giac(dinh)
print("Diện tích đa giác là:", dien_tich)

Diện tích đa giác là: 45.5


In [49]:
#Ứng dụng 2:
import sympy as sp
M = sp.Matrix([[0, 4, 1, 1], [4, 0, 0, 1], [3, 5, 2, 1], [2, 2, 5, 1]])
1/6*M.det()

-12.0000000000000

In [50]:
M = sp.Matrix([[0, 4, 1, 1], [4, 0, 0, 1], [3, 5, 2, 1], [2, 2, 5, 1]])
M.det()

-72

In [51]:
1/6*M.det()

-12.0000000000000

In [52]:
#Ứng dụng 3:
import numpy as np
def is_coplanar_matrix(A, B, C, D):
    M = np.array([
        [B[0]-A[0], B[1]-A[1], B[2]-A[2]],
        [C[0]-A[0], C[1]-A[1], C[2]-A[2]],
        [D[0]-A[0], D[1]-A[1], D[2]-A[2]]
    ])
    det = np.linalg.det(M)
    volume = abs(det) / 6
    return volume == 0
A = (1,2,3)
B = (4,5,6)
C = (7,8,9)
D = (10,11,12)
print("4 điểm cùng mặt phẳng?", is_coplanar_matrix(A, B, C, D))

4 điểm cùng mặt phẳng? True


In [57]:
#Ứng dụng 4:
from sympy import *
x, y, z = symbols('x y z')
MP = sp.Matrix([[x, y, z, 1],[-1, 3, 2, 1],[0, 1, 0, 1],[-2, 0, 1, 1]])
MP.det()

-4*x + 3*y - 5*z - 3

BÀI TẬP VỀ NHÀ

In [65]:
#Câu 1: Hãy viết chương trình để tính các ma trận:
import numpy as np
def minor_matrix(A, i, j):
    return np.delete(np.delete(A, i, axis=0), j, axis=1)
def cofactor_matrix(A):
    n = A.shape[0]
    C = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            minor = minor_matrix(A, i, j)
            C[i, j] = ((-1) ** (i + j)) * np.linalg.det(minor)
    return C
def adjoint_matrix(A):

    C = cofactor_matrix(A)
    return C.T
A = np.array([[1, 2, 3],
              [0, 4, 5],
              [1, 0, 6]])
C = cofactor_matrix(A)
Adj = adjoint_matrix(A)
print("Ma trận A:\n", A)
print("\nMa trận hệ số kép (cofactor matrix):\n", C)
print("\nMa trận liên hợp (adjoint matrix):\n", Adj)

Ma trận A:
 [[1 2 3]
 [0 4 5]
 [1 0 6]]

Ma trận hệ số kép (cofactor matrix):
 [[ 24.   5.  -4.]
 [-12.   3.   2.]
 [ -2.  -5.   4.]]

Ma trận liên hợp (adjoint matrix):
 [[ 24. -12.  -2.]
 [  5.   3.  -5.]
 [ -4.   2.   4.]]


In [66]:
#câu 2:
x, y = symbols('x y')
A = (1, 2)
B = (3, 5)
C = (4, 1)
M = Matrix([
    [A[0]**2 + A[1]**2, A[0], A[1], 1],
    [B[0]**2 + B[1]**2, B[0], B[1], 1],
    [C[0]**2 + C[1]**2, C[0], C[1], 1],
    [x**2 + y**2, x, y, 1]
])
circle_equation = M.det()
print("Phương trình đường tròn:", circle_equation)

Phương trình đường tròn: 11*x**2 - 65*x + 11*y**2 - 63*y + 136
