BÀI TẬP TRÊN LỚP

In [31]:
import numpy as np
D = np.array([[1,2],[3,4]])
np.copyto(E, D)
#lỗi do chưa khai báo E mà dùng copyto

In [7]:
E = np.array([[1,2],[3,5]])
np.copyto(E, D)

In [8]:
print(E)

[[1 2]
 [3 4]]


In [32]:
#1.2. Nên và không nên sử dụng kiểu dữ liệu numpy.matrix
x = np.array([['a','b'],['c','d']])
y = 'x'
C = np.array([[x, y], [1, 2]], dtype=object)
print(C)

[[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]


In [11]:
A = np.matrix([[[1,2],[3,4]],[[5,6],[7,8]]])
#matrix không hỗ trợ cho mảng nhiều hơn 2 chiều

ValueError: matrix must be 2-dimensional

In [12]:
A = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [33]:
#1.3. Đối tượng matrix từ các hàm trong gói numpy.matlib
from numpy import matlib
G = matlib.identity(5)
print (G)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
H = matlib.randn(3,2)
print(H)

[[-0.49510339 -0.01309657]
 [ 0.15950568 -0.10495173]
 [-0.0291177  -0.23836453]]


In [16]:
K = matlib.zeros([4,4])
print(K)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [34]:
#Sinh viên thực hiện tính toán số :
import numpy as np
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]
for i in range(len(c)):
  ci = np.array([[c[i], 1], [1, 0]], dtype=object)
  ci[0, 0] = c[i]
  if i == 0:
      M = ci
  else:
      M = M.dot(ci)
print("Ma trận kết quả:\n", M)
print("Xấp xỉ số π:", M[0, 0] / M[1, 0])

Ma trận kết quả:
 [[165707065 80143857]
 [52746197 25510582]]
Xấp xỉ số π: 3.1415926535897936


In [21]:
import numpy as np
X = np.array([[1,1],[1,2],[1,3],[1,4],[1,5]])
Y = np.array([[1],[2],[4],[4],[6]])
XT = X.T
A1 = np.linalg.inv(XT @ X)
A2 = XT @ Y
A = A1 @ A2
print("Hệ số hồi quy:")
print("a =", A[0,0])
print("b =", A[1,0])

Hệ số hồi quy:
a = -0.19999999999999662
b = 1.2000000000000008


BÀI TẬP VỀ NHÀ

In [26]:
def bpcuctieu(a):
  b = []
  o1 = []
  for i in range(len(a)):
    o1.append(1.0)
    b.append((i+1)*1.0)
  x = np.array([o1, b])
  u = np.dot(x, x.T)
  y = np.array(a)
  from numpy import linalg
  u_1 =np.linalg.inv(u)
  v = np.dot(u_1, x)
  A = np.dot(v, y)
  return A
print(bpcuctieu([10.0, 8,7,5,2]))

[12.1 -1.9]
