#Bai Tap Tren Lop

In [ ]:
#1. Dẫn nhập – Một số hàm về xử lý vector với Python
def scale(a, v):
  return [a*vi for vi in v]
v = [3,5,7]
scale(10, v)

[30, 50, 70]

In [ ]:
def sumvector(v, w):
  return [vi+wi for (vi, wi) in zip(v, w)]
v = [3,5,7]
w = [2,4,6]
sumvector(v, w)

[5, 9, 13]

In [ ]:
def dotvector(v, w):
  return sum([vi*wi for (vi, wi) in zip(v, w)])
dotvector(v, w)

68

In [ ]:
def lenvector(v):
  return dotvector(v,v)
lenvector(w)

56

In [ ]:
#2. Bài toán ứng dụng 1 – Phân loại tuyến tính
import numpy as np
scores  = np.array([-1, 1, 2, -3, 5, -4])
scores >= 0

array([False,  True,  True, False,  True, False])

In [ ]:
scores < 0

array([ True, False, False,  True, False,  True])

In [ ]:
np.select([scores >= 0, scores < 0], ['so duong', 'so am'], default='khong xac dinh')

array(['so am', 'so duong', 'so duong', 'so am', 'so duong', 'so am'],
      dtype='<U14')

In [ ]:
scores  = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
np.select([scores >0, scores ==0, scores < 0],['so duong', 'so 0', 'so am'], default='khong xac dinh')

array(['so am', 'so duong', 'so duong', 'so 0', 'so am', 'so duong',
       'so 0', 'so am'], dtype='<U14')

In [ ]:
#3. Thực hành xử lý ma trận
import numpy as np
import numpy as np
from scipy import linalg, sparse
D = np.asmatrix([ [3,4], [5,6] ])
print(D)

[[3 4]
 [5 6]]


In [ ]:
C = np.asmatrix(np.random.random((5,7)))
print(C)

[[0.8654149  0.13599874 0.90476338 0.45039373 0.50957153 0.3745783
  0.39274925]
 [0.31312589 0.3821081  0.80015125 0.52887977 0.93022967 0.84192354
  0.50609722]
 [0.17324731 0.42286709 0.23407283 0.08115    0.55103819 0.29438274
  0.03725905]
 [0.15156697 0.47634587 0.3523153  0.60473931 0.26806096 0.03025916
  0.81998815]
 [0.40711547 0.89582812 0.56418698 0.56492409 0.52880355 0.17557185
  0.03298561]]


In [ ]:
A = np.asmatrix(np.random.random((2,2)))
print(A)

[[0.06588782 0.92559338]
 [0.52976495 0.35100732]]


In [ ]:
b = np.array([(1+5j, 2j, 3j),(4, 5, 6)])
B = np.asmatrix(b)
print(b)
print(B)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [ ]:
A.T

matrix([[0.06588782, 0.52976495],
        [0.92559338, 0.35100732]])

In [ ]:
A.I

matrix([[-0.75126804,  1.98106617],
        [ 1.1338666 , -0.14102103]])

In [ ]:
linalg.inv(A)
M = np.array([[-1,3,2],[0,2,1],[1,5,-2]])
M_lower = np.tril(M)
print(M_lower)

[[-1  0  0]
 [ 0  2  0]
 [ 1  5 -2]]


In [ ]:
M = np.array([[-1,3,2],[0,2,1],[1,5,-2]])
M_upper = np.triu(M)
print(M_upper)

[[-1  3  2]
 [ 0  2  1]
 [ 0  0 -2]]


In [ ]:
M = np.array([[-1,3,2],[0,2,1],[1,5,-2]])
v_diag = np.diag(M)
print (v_diag)
M_diag = np.diag(v_diag)
print (M_diag)

[-1  2 -2]
[[-1  0  0]
 [ 0  2  0]
 [ 0  0 -2]]


In [ ]:
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
sp.solve([x*x+2-6, y-1-6,x+z-1, 2*x*x-8, z*z+4-5,y-z-8], [x, y, z])

[(2, 7, -1)]

In [ ]:
x = [1, 2, 3]
y = [1, 2, 3]
print(all([x[i] == y[i] for i in range(len(x))]))

True


In [ ]:
y = [1, 2, 4]
print(all([x[i] == y[i] for i in range(len(x))]))

False


In [ ]:
import numpy as np
np.array_equal([1, 2], [1, 2])

True

In [ ]:
np.array_equal(np.array([1, 2]), np.array([1, 2]))

True

In [ ]:
import numpy as np
A = np.reshape(np.arange(36.0), (6,6))
print(A)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]


In [ ]:
I6 = np.identity(6)
print(I6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
A.size

36

In [ ]:
np.matrix.diagonal(A)

array([ 0.,  7., 14., 21., 28., 35.])

In [ ]:
A = A + I6
print(A)

[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


In [ ]:
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print(C)

[ 71. 198. 325. 452. 579. 706.]


In [ ]:
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print(D)

[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]


In [ ]:
import numpy as np
A = np.reshape(np.arange(36.0), (6,6))
I6 = np.identity(6)
A = A + I6
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
E = A.dot(D.T)
print(E)

[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


In [ ]:
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0], [5., 1], [6., 0.]])
G = A.dot(F)
print(F)

[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]


In [ ]:
print(G)

[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


In [ ]:
np.linalg.inv(A)

array([[ 0.37022901, -0.45610687, -0.28244275, -0.10877863,  0.0648855 ,
         0.23854962],
       [-0.44656489,  0.65839695, -0.23664122, -0.13167939, -0.02671756,
         0.07824427],
       [-0.26335878, -0.22709924,  0.80916031, -0.15458015, -0.11832061,
        -0.08206107],
       [-0.08015267, -0.11259542, -0.14503817,  0.82251908, -0.20992366,
        -0.24236641],
       [ 0.10305344,  0.0019084 , -0.09923664, -0.20038168,  0.69847328,
        -0.40267176],
       [ 0.28625954,  0.11641221, -0.05343511, -0.22328244, -0.39312977,
         0.4370229 ]])

In [ ]:
np.linalg.inv(np.linalg.inv(A))

array([[ 1.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  8.,  8.,  9., 10., 11.],
       [12., 13., 15., 15., 16., 17.],
       [18., 19., 20., 22., 22., 23.],
       [24., 25., 26., 27., 29., 29.],
       [30., 31., 32., 33., 34., 36.]])

In [ ]:
#4. Bài toán ứng dụng 2 – Tính toán dãy Fibonacci: Con đường tìm đến tỉ số vàng!
import numpy as np
A = np.array( [ [1,1], [1,0] ] )
b = np.array([1, 0])
n = 10
for i in range(n):
  b = A.dot(b)
  print(b)

[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]


In [ ]:
import sympy as sp
from sympy import Symbol
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520
nghiem = sp.solve((pt1, pt2, pt3, pt4))
nghiem

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}

In [ ]:
import numpy as np
A = np.matrix([[1, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, 1, 0],
               [0, 0, 0, 1]])
A_nghichdao = np.linalg.inv(A)
print(A_nghichdao)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


BÀI TẬP VỀ NHÀ

In [ ]:
#câu 1
import numpy as np
A1 = np.array([[1, -1], [2, 3]])
b1 = np.array([-2, 6])
sol1 = np.linalg.solve(A1, b1)
print(sol1)

[0. 2.]


In [ ]:
A2 = np.array([[1, -1, 0], [2, -1, -1], [1, 1, 1]])
b2 = np.array([2, 3, 6])
sol2 = np.linalg.solve(A2, b2)
print(sol2)

[3. 1. 2.]


In [ ]:
A3 = np.array([[1, 1, 1], [4, 2, 1], [9, 3, 1]])
b3 = np.array([4, 3, 4])
sol3 = np.linalg.solve(A3, b3)
print(sol3)

[ 1. -4.  7.]


In [ ]:
A4 = np.array([[1, 0, 1], [1, 1, -2], [-2, 2, 1]])
b4 = np.array([1, -3, 0])
sol4 = np.linalg.solve(A4, b4)
print(sol4)

[-0.11111111 -0.66666667  1.11111111]


In [ ]:
#câu 2
from sympy import symbols, Eq, solve, Matrix
x, y = symbols('x y')
eq1 = Eq(x - y, -2)
eq2 = Eq(2*x + 3*y, 6)
sol1 = solve((eq1, eq2), (x, y))
print(sol1)

{x: 0, y: 2}


In [ ]:
x, y, z = symbols('x y z')
eq3 = Eq(x - y, 2)
eq4 = Eq(2*x - y - z, 3)
eq5 = Eq(x + y + z, 6)
sol2 = solve((eq3, eq4, eq5), (x, y, z))
print(sol2)

{x: 3, y: 1, z: 2}


In [ ]:
a, b, c = symbols('a b c')
eq6 = Eq(a + b + c, 4)
eq7 = Eq(4*a + 2*b + c, 3)
eq8 = Eq(9*a + 3*b + c, 4)
sol3 = solve((eq6, eq7, eq8), (a, b, c))
print(sol3)

{a: 1, b: -4, c: 7}


In [ ]:
eq9 = Eq(a + c, 1)
eq10 = Eq(a + b - 2*c, -3)
eq11 = Eq(-2*a + 2*b + c, 0)
sol4 = solve((eq9, eq10, eq11), (a, b, c))
print(sol4)

{a: -1/9, b: -2/3, c: 10/9}


In [ ]:
#câu 3
from sympy import Matrix, pprint
def fibonacci_matrix(k):
    F = Matrix([[1, 1], [1, 0]])
    return F**k
def fibonacci_sequence(n):
    fib = [0, 1]
    for _ in range(2, n + 1):
        fib.append(fib[-1] + fib[-2])
    return fib
n = 10
fib = fibonacci_sequence(n + 1)
for k in range(1, n + 1):
    Fk = fibonacci_matrix(k)
    a = Fk[0, 0]
    b = Fk[0, 1]
    c = Fk[1, 1]
    print(f"F^{k} =")
    pprint(Fk)
    print(f"=> Fib_{k+1} = {a}, Fib_{k} = {b}, Fib_{k-1} = {c}")
    print(f"Check: {a == fib[k+1] and b == fib[k] and c == fib[k-1]}")
    print()

F^1 =
⎡1  1⎤
⎢    ⎥
⎣1  0⎦
=> Fib_2 = 1, Fib_1 = 1, Fib_0 = 0
Check: True

F^2 =
⎡2  1⎤
⎢    ⎥
⎣1  1⎦
=> Fib_3 = 2, Fib_2 = 1, Fib_1 = 1
Check: True

F^3 =
⎡3  2⎤
⎢    ⎥
⎣2  1⎦
=> Fib_4 = 3, Fib_3 = 2, Fib_2 = 1
Check: True

F^4 =
⎡5  3⎤
⎢    ⎥
⎣3  2⎦
=> Fib_5 = 5, Fib_4 = 3, Fib_3 = 2
Check: True

F^5 =
⎡8  5⎤
⎢    ⎥
⎣5  3⎦
=> Fib_6 = 8, Fib_5 = 5, Fib_4 = 3
Check: True

F^6 =
⎡13  8⎤
⎢     ⎥
⎣8   5⎦
=> Fib_7 = 13, Fib_6 = 8, Fib_5 = 5
Check: True

F^7 =
⎡21  13⎤
⎢      ⎥
⎣13  8 ⎦
=> Fib_8 = 21, Fib_7 = 13, Fib_6 = 8
Check: True

F^8 =
⎡34  21⎤
⎢      ⎥
⎣21  13⎦
=> Fib_9 = 34, Fib_8 = 21, Fib_7 = 13
Check: True

F^9 =
⎡55  34⎤
⎢      ⎥
⎣34  21⎦
=> Fib_10 = 55, Fib_9 = 34, Fib_8 = 21
Check: True

F^10 =
⎡89  55⎤
⎢      ⎥
⎣55  34⎦
=> Fib_11 = 89, Fib_10 = 55, Fib_9 = 34
Check: True

