BÀI TẬP TRÊN LỚP

In [ ]:
#1.1. Một số phép xử lý ma trận của NumPy và Scipy
from scipy import linalg
import numpy as np
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]])
A = np.matrix(np.random.random((2,2)))
B = np.asmatrix(b)
C = np.asmatrix(np.random.random( (10,5) ) )
D = np.asmatrix([[4,3],[2,6]])
F = np.eye(3, k=1)
print(a)

[1 2 3]


In [ ]:
print(b)

[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]


In [ ]:
print(c)

[[[ 0.5  1.5 10. ]
  [ 3.   2.   1. ]]

 [[ 6.   5.   4. ]
  [ 7.   8.   9. ]]]


In [ ]:
print(A)

[[0.71789119 0.96162139]
 [0.04198656 0.24518689]]


In [ ]:
print(B)

[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]


In [ ]:
print(C)

[[0.26151528 0.6459644  0.65601326 0.13212675 0.72318339]
 [0.96579301 0.90387936 0.91735415 0.09979436 0.63351851]
 [0.32837944 0.07590012 0.12632595 0.99889111 0.3800526 ]
 [0.226316   0.85663014 0.14024295 0.71723912 0.928032  ]
 [0.34506699 0.03353807 0.47268816 0.0169421  0.86956186]
 [0.7697958  0.62201014 0.08149457 0.6536555  0.65340229]
 [0.53135628 0.05880282 0.55913934 0.06122421 0.58995311]
 [0.82634627 0.92882875 0.61570465 0.0875968  0.73406259]
 [0.32756951 0.41061142 0.7316741  0.0890835  0.3175727 ]
 [0.20953356 0.46131157 0.49999564 0.93212718 0.41297916]]


In [ ]:
print(D)

[[4 3]
 [2 6]]


In [ ]:
print(F)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
F = np.eye(3, k=0)
print(F)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
F = np.eye(3, k=-1)
print(F)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
print(np.linalg.matrix_rank(C))

5


In [ ]:
print(A.I)

[[ 1.80759855 -7.08938965]
 [-0.30953874  5.29253033]]


In [ ]:
print(linalg.inv(A))

[[ 1.80759855 -7.08938965]
 [-0.30953874  5.29253033]]


In [ ]:
print(linalg.det(A))

0.13564233867057587


In [ ]:
print(A.T)

[[0.71789119 0.04198656]
 [0.96162139 0.24518689]]


In [ ]:
print(A.H)

[[0.71789119 0.04198656]
 [0.96162139 0.24518689]]


In [ ]:
print(linalg.solve(A, b))

[[ 1.80759855-12.08917167j  0.        -31.83175115j
   0.        -37.11354226j]
 [-0.30953874+18.38427265j  0.        +25.84357416j
   0.        +30.82656575j]]


In [ ]:
E = np.asmatrix(a).T
print(E)

[[1]
 [2]
 [3]]


In [ ]:
print(linalg.lstsq(F, E))

(array([[2.],
       [3.],
       [0.]]), array([], dtype=float64), 2, array([1., 1., 0.]))


In [ ]:
print(np.add(A, D))

[[4.71789119 3.96162139]
 [2.04198656 6.24518689]]


In [ ]:
print(np.subtract(A, D))

[[-3.28210881 -2.03837861]
 [-1.95801344 -5.75481311]]


In [ ]:
print(np.divide(A, D))

[[0.1794728  0.32054046]
 [0.02099328 0.04086448]]


In [ ]:
print(A @ D)

[[4.79480755 7.92340193]
 [0.65832002 1.59708104]]


In [ ]:
print(np.multiply(D, A))

matrix([[2.87156477, 2.88486418],
        [0.08397312, 1.47112137]])

In [ ]:
print(np.dot(A, D))

[[4.79480755 7.92340193]
 [0.65832002 1.59708104]]


In [ ]:
print(np.vdot(A, D))

[[2.87156477]]


In [ ]:
print(linalg.expm(A))

[[2.08578992 1.58153045]
 [0.06905319 1.30835688]]


In [ ]:
print(linalg.logm(A))

[[-0.41574506  2.37248701]
 [ 0.10358813 -1.58198866]]


In [ ]:
#2.3. Ma trận hội tụ
import numpy as np
A = np.array([ [0,1], [1,0]])
print(A)

[[0 1]
 [1 0]]


In [ ]:
temp = A.dot(A)
print(temp)

[[1 0]
 [0 1]]


In [ ]:
k= 6
for i in range(k-1):
    temp = temp.dot(A)
    print (temp)
    print('---')

[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---


In [ ]:
B = np.array([ [0,-1], [-1,0]])
print(B)

[[ 0 -1]
 [-1  0]]


In [ ]:
temp = B.dot(B)
print(temp)

[[1 0]
 [0 1]]


In [ ]:
k= 5
for i in range(k-1):
  temp = temp.dot(B)
  print (temp)
print('---')

[[ 0 -1]
 [-1  0]]
[[1 0]
 [0 1]]
[[ 0 -1]
 [-1  0]]
[[1 0]
 [0 1]]
---


In [ ]:
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print(C)

[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]


In [ ]:
temp = C.dot(C)
print(temp)

[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]


In [ ]:
 k= 1000
for i in range(k-1):
  temp = temp.dot(C)
print(temp)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
k= 1000
for i in range(k-1):
  temp = temp.dot(C)
print(temp)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#2.4. Ma trận Markov
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M)
print (MM)

[[0.7  0.45]
 [0.3  0.55]]


In [ ]:
MM = M.dot(M)
print (MM)

[[0.7  0.45]
 [0.3  0.55]]


In [ ]:
for i in range(100):
  MM = MM.dot(M)
print (MM)

[[0.6 0.6]
 [0.4 0.4]]


In [ ]:
#3.2. Phân rã ma trận LU
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M)
print (P)

[[1. 0.]
 [0. 1.]]


In [ ]:
print(L)

[[1.   0.  ]
 [0.25 1.  ]]


In [ ]:
print(U)

[[0.8   0.3  ]
 [0.    0.625]]


In [ ]:
print(L.dot(U))

[[0.8 0.3]
 [0.2 0.7]]


In [ ]:
#5. Bài toán ứng dụng 2 – Bài toán loan tin
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
temp = A.dot(A)
print(temp)

[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]


In [ ]:
temp = temp.dot(A)
print(temp)

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [ ]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k-1):
  temp = temp.dot(A)
  sumA = sumA + temp
print (temp)
print (sumA)

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


In [1]:
import numpy as np

# a. Chọn ma trận khả nghịch 3x3
A = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 0, 0]])
print("Ma trận A:")
print(A)

# Kiểm tra khả nghịch
det_A = np.linalg.det(A)
print(f"Định thức của A: {det_A}")
assert det_A != 0, "Ma trận không khả nghịch!"
# b. Chuỗi đầu vào
text = "NguyenVanA"
print(f"Chuỗi gốc: {text}")
# c. Chuyển văn bản sang vector số
def text_to_vector(text):
    vec = [ord(c) for c in text]
    while len(vec) % 3 != 0:
        vec.append(0)
    return np.array(vec).reshape(-1, 3).T
P = text_to_vector(text)
print("Vector P (mã ASCII):")
print(P)
# d. Mã hóa
C = A @ P
print("Bản mã C:")
print(C)
# Giải mã
A_inv = np.linalg.inv(A)
P_decoded = A_inv @ C
decoded_text = ''.join([chr(round(num)) for num in P_decoded.T.flatten() if round(num) > 0])
print("Giải mã văn bản:")
print(decoded_text)

Ma trận A:
[[2 1 1]
 [1 3 2]
 [1 0 0]]
Định thức của A: -1.0
Chuỗi gốc: NguyenVanA
Vector P (mã ASCII):
[[ 78 121  86  65]
 [103 101  97   0]
 [117 110 110   0]]
Bản mã C:
[[376 453 379 130]
 [621 644 597  65]
 [ 78 121  86  65]]
Giải mã văn bản:
NguyenVanA


In [ ]:
import numpy as np

def continued_fraction_pq(coeffs):
    print(f"Chuỗi hệ số: {coeffs}")
    M = np.array([[coeffs[0], 1],
                  [1, 0]])
    print(f"M0:\n{M}")

    for i, c in enumerate(coeffs[1:], 1):
        M_step = np.array([[c, 1],
                           [1, 0]])
        print(f"Bước {i}: Nhân với\n{M_step}")
        M = M @ M_step
        print(f"Kết quả sau bước {i}:\n{M}")

    result = M @ np.array([1, 0])
    pn, qn = result
    print(f"p_n = {pn}, q_n = {qn}")
    return pn, qn

# Ví dụ: 8/3 → [3, 1, 2] (tức 3 + 1/(1 + 1/2))
coeffs = [3, 1, 2]
pn, qn = continued_fraction_pq(coeffs)

print(f"\n=> Phân số: {pn}/{qn} = {pn / qn}")


Chuỗi hệ số: [3, 1, 2]
M0:
[[3 1]
 [1 0]]
Bước 1: Nhân với
[[1 1]
 [1 0]]
Kết quả sau bước 1:
[[4 3]
 [1 1]]
Bước 2: Nhân với
[[2 1]
 [1 0]]
Kết quả sau bước 2:
[[11  4]
 [ 3  1]]
p_n = 11, q_n = 3

=> Phân số: 11/3 = 3.6666666666666665
