BÀI TẬP TRÊN LỚP

In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
tich = np.inner(a,b)
print(tich)

32


In [3]:
print(np.dot(a,b))

32


In [5]:
import numpy as np
a = np.array([1,2,-3])
print(np.linalg.norm(a))

3.7416573867739413


In [6]:
a = np.array([1,2,-3])
print(np.linalg.norm(a,1))

6.0


In [7]:
def chuan(v, k):
    tong = 0
    for i in range(len(v)):
        tong = tong + abs(v[i]**k)
    ketqua = math.pow(tong, 1.0/k)
    return ketqua

In [8]:
import math
import numpy as np
a = np.array([1,2,-3])
chuan(a, 1)

6.0

In [9]:
print(np.linalg.norm(a,1))

6.0


In [10]:
print(chuan(a, 2))

3.7416573867739413


In [11]:
print(np.linalg.norm(a,2))

3.7416573867739413


In [12]:
print(chuan(a, 3))

3.3019272488946263


In [13]:
print(np.linalg.norm(a,3))

3.3019272488946263


In [14]:
print(chuan(a, 1000))

1.0442214818467515


In [15]:
print(np.linalg.norm(a,1000))

inf


/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


In [17]:
from scipy import linalg
print(linalg.norm(a))

3.7416573867739413


In [18]:
print(linalg.norm(a, 100))

3.0


In [19]:
print(linalg.norm(a, 1000))

inf


/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


In [20]:
import numpy as np
m = 10
v1 = np.array([5,-4,3])
v2 = np.array([4,3,-2])
v3 = np.array([-4,-3,-1])
v4 = np.array([-9,8,6])
mi = np.array([2,5,2,1])
M = np.array([v1,v2,v3,v4])
MT = M.transpose()
print(MT)

[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]


In [22]:
v = (1.0/m)*MT.dot(mi)
print (v)

[1.3 0.9 0. ]


In [23]:
import numpy as np
A = np.array([[0.998, 0.136],
              [0.002, 0.864]])
v0 = np.array([0.95, 0.05])
vt = np.linalg.matrix_power(A, 100).dot(v0)
print(vt)

[0.98550723 0.01449277]


In [24]:
import numpy as np
A = np.array([[0.998, 0.136],
              [-0.002, 0.864]])
A_100 = np.eye(2)
for _ in range(100):
    A_100 = np.dot(A_100, A)
v0 = np.array([[0.95],
               [0.05]])
v100 = np.dot(A_100, v0)
print("Ma trận A^100:")
print(A_100)
print("Vector trạng thái sau 100 tuần:")
print(v100)

Ma trận A^100:
[[ 0.67622106  0.69703713]
 [-0.01025055 -0.01056553]]
Vector trạng thái sau 100 tuần:
[[ 0.67726186]
 [-0.0102663 ]]


In [25]:
import numpy as np
A = np.array([[1, -68],
              [1, 1]])
b = np.array([0, 1])
solution = np.linalg.solve(A, b)
print("Nghiệm của hệ phương trình là:")
print(f"x = {solution[0]}")
print(f"y = {solution[1]}")

Nghiệm của hệ phương trình là:
x = 0.9855072463768116
y = 0.014492753623188406


In [26]:
import sympy as sym
x, y = sym.symbols('x y')
xy = sym.Matrix([x,y])
A = sym.Matrix([[1, -68],[1,1]])
v = sym.Matrix([0, 1])
nghiem = sym.solve([A*xy-v])
print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [27]:
import numpy as np
A = np.array([[1, 6],
              [5, 2]])
u = np.array([[6],
              [-5]])
Au = A @ u
result = -4 * u
print("Au =\n", Au)
print("-4 * u =\n", result)
print("Hai vector có bằng nhau không? =>", np.allclose(Au, result))


Au =
 [[-24]
 [ 20]]
-4 * u =
 [[-24]
 [ 20]]
Hai vector có bằng nhau không? => True


In [28]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I - A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])

[-7.000, 3.000]


In [29]:
print (sympy.pretty(nghiem))

[-7, 3]


In [30]:
import sympy as sp
x, y = sp.symbols('x y')
vec = sp.Matrix([x, y])
A = sp.Matrix([[2, 3],
               [3, -6]])
lambda_val = 3
I = sp.eye(2)
eig_matrix = A - lambda_val * I
phuongtrinh = eig_matrix * vec
nghiem = sp.solve(phuongtrinh, (x, y), dict=True)
print(nghiem)

[{x: 3*y}]


In [31]:
import numpy as np
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1 = LA.inv(P)
print (P1)

[[-0.3  0.9]
 [ 0.3  0.1]]


In [33]:
print(P1**-1)

[[-3.33333333  1.11111111]
 [ 3.33333333 10.        ]]


In [35]:
print(A.dot(P))

[[ 2.33333333  9.        ]
 [-7.          3.        ]]


In [37]:
print(P.dot(D))

[[ 2.33333333  9.        ]
 [-7.          3.        ]]


In [38]:
P @ (D ** 1000) @ P1

array([[ 5.03503397e+18,  3.50482117e+18],
       [ 3.50482117e+18, -4.31115581e+18]])

In [39]:
print (D **2)

[[49  0]
 [ 0  9]]


BÀI TẬP VỀ NHÀ

In [ ]:
Câu 1: [Trắc nghiệm] Trong Python 3, các câu lệnh sau đây, câu lệnh nào tính chuẩn 2 của
vector a. Với a được xác định là:
>>> import numpy as np
>>> a = np.array([1,2,3])
a. >>> mag = np.sqrt(a.dot(a))
b. >>> mag = np.sqrt(a @ a )
c. >>> mag = np.sqrt(np.inner(a,a))
d. >>> mag = lambda x : math.sqrt(sum(i** 2 for i in x))
>>> mag(a)

###tôi chọn đáp án a

In [40]:
#a
import numpy as np
u = np.array([1, 2])
v = np.array([3, 4])
khoang_cach = np.linalg.norm(u - v)
print("Khoảng cách giữa u và v là:", khoang_cach)

Khoảng cách giữa u và v là: 2.8284271247461903


In [41]:
#b
tich_vo_huong = np.dot(u, v)
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)
cos_theta = tich_vo_huong / (norm_u * norm_v)
theta = np.arccos(cos_theta)
theta_do = np.degrees(theta)
print("Góc giữa u và v (radian):", theta)
print("Góc giữa u và v (độ):", theta_do)

Góc giữa u và v (radian): 0.17985349979247847
Góc giữa u và v (độ): 10.304846468766044


In [42]:
#c
phep_chieu = (np.dot(u, v) / np.dot(v, v)) * v
print("Phép chiếu của u lên v là:", phep_chieu)

Phép chiếu của u lên v là: [1.32 1.76]
